:- dynamic coin/2.

initializeCoins :-
  assert(coin(gold,5)),
  playerCount(PlayerCount),
  ((PlayerCount == 4,
    assert(coin(white,7)),
    assert(coin(blue,7)),
    assert(coin(green,7)),
    assert(coin(red,7)),
    assert(coin(black,7))
  );
  C is PlayerCount + 2,
  assert(coin(white,C)),
  assert(coin(blue,C)),
  assert(coin(green,C)),
  assert(coin(red,C)),
  assert(coin(black,C))).

updateCoinsGUI :-
  coin(white, White),
  coin(blue, Blue),
  coin(green, Green),
  coin(red, Red),
  coin(black, Black),
  coin(gold, Gold),
  free(@bwhite),
  free(@bblue),
  free(@bgreen),
  free(@bred),
  free(@bblack),
  free(@bgold),
  send(@main, display, new(@bgold,text(Gold,center,large)), point(612, 50)),
  send(@main, display, new(@bblack,text(Black,center,large)), point(612, 97)),
  send(@main, display, new(@bwhite,text(White,center,large)), point(612, 144)),
  send(@main, display, new(@bred,text(Red,center,large)), point(612, 191)),
  send(@main, display, new(@bblue,text(Blue,center,large)), point(612, 238)),
  send(@main, display, new(@bgreen,text(Green,center,large)), point(612, 285)).


updatePlayerPowersGUI :-
  playerCount(PlayerCount),
  (
    (
      PlayerCount == 2,
      playerNo(1,X),
      playerNo(2,Y),

      cardPower(X,XCardWhite,XCardBlue,XCardGreen,XCardRed,XCardBlack),
      coinPower(X,XCoinWhite,XCoinBlue,XCoinGreen,XCoinRed,XCoinBlack,XCoinGold),
      prestigePower(X,XPrestige),
      XTotalCoin is XCoinWhite+XCoinBlue+XCoinGreen+XCoinRed+XCoinBlack+XCoinGold,
      free(@xtotalcoin),free(@xprestige),
      free(@xcardwhite),free(@xcardblue),free(@xcardgreen),free(@xcardred),free(@xcardblack),
      free(@xcoinwhite),free(@xcoinblue),free(@xcoingreen),free(@xcoinred),free(@xcoinblack),free(@xcoingold),
      send(@main, display, new(@xprestige,text(XPrestige,center,large)), point(44, 456)),
      send(@main, display, new(@xtotalcoin,text(XTotalCoin,center,large)), point(35, 489)),
      send(@main, display, new(@xcoingold,text(XCoinGold,center,large)), point(62, 514)),
      send(@main, display, new(@xcardwhite,text(XCardWhite,center,large)), point(80, 489)),
      send(@main, display, new(@xcoinwhite,text(XCoinWhite,center,large)), point(100, 489)),
      send(@main, display, new(@xcardgreen,text(XCardBlue,center,large)), point(122, 489)),
      send(@main, display, new(@xcoinblue,text(XCoinBlue,center,large)), point(144, 489)),
      send(@main, display, new(@xcardblue,text(XCardGreen,center,large)), point(167, 489)),
      send(@main, display, new(@xcoingreen,text(XCoinGreen,center,large)), point(188, 489)),
      send(@main, display, new(@xcardred,text(XCardRed,center,large)), point(210, 489)),
      send(@main, display, new(@xcoinred,text(XCoinRed,center,large)), point(230, 489)),
      send(@main, display, new(@xcardblack,text(XCardBlack,center,large)), point(252, 489)),
      send(@main, display, new(@xcoinblack,text(XCoinBlack,center,large)), point(274, 489)),

      cardPower(Y,YCardWhite,YCardBlue,YCardGreen,YCardRed,YCardBlack),
      coinPower(Y,YCoinWhite,YCoinBlue,YCoinGreen,YCoinRed,YCoinBlack,YCoinGold),
      prestigePower(Y,YPrestige),
      YTotalCoin is YCoinWhite+YCoinBlue+YCoinGreen+YCoinRed+YCoinBlack+YCoinGold,
      free(@ytotalcoin),free(@yprestige),
      free(@ycardwhite),free(@ycardblue),free(@ycardgreen),free(@ycardred),free(@ycardblack),
      free(@ycoinwhite),free(@ycoinblue),free(@ycoingreen),free(@ycoinred),free(@ycoinblack),free(@ycoingold),
      send(@main, display, new(@yprestige,text(YPrestige,center,large)), point(307, 456)),
      send(@main, display, new(@ytotalcoin,text(YTotalCoin,center,large)), point(298, 489)),
      send(@main, display, new(@ycoingold,text(YCoinGold,center,large)), point(326, 514)),
      send(@main, display, new(@ycardwhite,text(YCardWhite,center,large)), point(343, 489)),
      send(@main, display, new(@ycoinwhite,text(YCoinWhite,center,large)), point(363, 489)),
      send(@main, display, new(@ycardgreen,text(YCardBlue,center,large)), point(385, 489)),
      send(@main, display, new(@ycoinblue,text(YCoinBlue,center,large)), point(407, 489)),
      send(@main, display, new(@ycardblue,text(YCardGreen,center,large)), point(430, 489)),
      send(@main, display, new(@ycoingreen,text(YCoinGreen,center,large)), point(451, 489)),
      send(@main, display, new(@ycardred,text(YCardRed,center,large)), point(473, 489)),
      send(@main, display, new(@ycoinred,text(YCoinRed,center,large)), point(493, 489)),
      send(@main, display, new(@ycardblack,text(YCardBlack,center,large)), point(515, 489)),
      send(@main, display, new(@ycoinblack,text(YCoinBlack,center,large)), point(538, 489))
    );
    (
      PlayerCount == 3,
      playerNo(1,X),
      playerNo(2,Y),
      playerNo(3,Z),

      cardPower(X,XCardWhite,XCardBlue,XCardGreen,XCardRed,XCardBlack),
      coinPower(X,XCoinWhite,XCoinBlue,XCoinGreen,XCoinRed,XCoinBlack,XCoinGold),
      prestigePower(X,XPrestige),
      XTotalCoin is XCoinWhite+XCoinBlue+XCoinGreen+XCoinRed+XCoinBlack+XCoinGold,
      free(@xtotalcoin),free(@xprestige),
      free(@xcardwhite),free(@xcardblue),free(@xcardgreen),free(@xcardred),free(@xcardblack),
      free(@xcoinwhite),free(@xcoinblue),free(@xcoingreen),free(@xcoinred),free(@xcoinblack),free(@xcoingold),
      send(@main, display, new(@xprestige,text(XPrestige,center,large)), point(44, 456)),
      send(@main, display, new(@xtotalcoin,text(XTotalCoin,center,large)), point(35, 489)),
      send(@main, display, new(@xcoingold,text(XCoinGold,center,large)), point(62, 514)),
      send(@main, display, new(@xcardwhite,text(XCardWhite,center,large)), point(80, 489)),
      send(@main, display, new(@xcoinwhite,text(XCoinWhite,center,large)), point(100, 489)),
      send(@main, display, new(@xcardgreen,text(XCardBlue,center,large)), point(122, 489)),
      send(@main, display, new(@xcoinblue,text(XCoinBlue,center,large)), point(144, 489)),
      send(@main, display, new(@xcardblue,text(XCardGreen,center,large)), point(167, 489)),
      send(@main, display, new(@xcoingreen,text(XCoinGreen,center,large)), point(188, 489)),
      send(@main, display, new(@xcardred,text(XCardRed,center,large)), point(210, 489)),
      send(@main, display, new(@xcoinred,text(XCoinRed,center,large)), point(230, 489)),
      send(@main, display, new(@xcardblack,text(XCardBlack,center,large)), point(252, 489)),
      send(@main, display, new(@xcoinblack,text(XCoinBlack,center,large)), point(274, 489)),

      cardPower(Y,YCardWhite,YCardBlue,YCardGreen,YCardRed,YCardBlack),
      coinPower(Y,YCoinWhite,YCoinBlue,YCoinGreen,YCoinRed,YCoinBlack,YCoinGold),
      prestigePower(Y,YPrestige),
      YTotalCoin is YCoinWhite+YCoinBlue+YCoinGreen+YCoinRed+YCoinBlack+YCoinGold,
      free(@ytotalcoin),free(@yprestige),
      free(@ycardwhite),free(@ycardblue),free(@ycardgreen),free(@ycardred),free(@ycardblack),
      free(@ycoinwhite),free(@ycoinblue),free(@ycoingreen),free(@ycoinred),free(@ycoinblack),free(@ycoingold),
      send(@main, display, new(@yprestige,text(YPrestige,center,large)), point(307, 456)),
      send(@main, display, new(@ytotalcoin,text(YTotalCoin,center,large)), point(298, 489)),
      send(@main, display, new(@ycoingold,text(YCoinGold,center,large)), point(326, 514)),
      send(@main, display, new(@ycardwhite,text(YCardWhite,center,large)), point(343, 489)),
      send(@main, display, new(@ycoinwhite,text(YCoinWhite,center,large)), point(363, 489)),
      send(@main, display, new(@ycardgreen,text(YCardBlue,center,large)), point(385, 489)),
      send(@main, display, new(@ycoinblue,text(YCoinBlue,center,large)), point(407, 489)),
      send(@main, display, new(@ycardblue,text(YCardGreen,center,large)), point(430, 489)),
      send(@main, display, new(@ycoingreen,text(YCoinGreen,center,large)), point(451, 489)),
      send(@main, display, new(@ycardred,text(YCardRed,center,large)), point(473, 489)),
      send(@main, display, new(@ycoinred,text(YCoinRed,center,large)), point(493, 489)),
      send(@main, display, new(@ycardblack,text(YCardBlack,center,large)), point(515, 489)),
      send(@main, display, new(@ycoinblack,text(YCoinBlack,center,large)), point(538, 489)),

      cardPower(Z,ZCardWhite,ZCardBlue,ZCardGreen,ZCardRed,ZCardBlack),
      coinPower(Z,ZCoinWhite,ZCoinBlue,ZCoinGreen,ZCoinRed,ZCoinBlack,ZCoinGold),
      prestigePower(Z,ZPrestige),
      ZTotalCoin is ZCoinWhite+ZCoinBlue+ZCoinGreen+ZCoinRed+ZCoinBlack+ZCoinGold,
      free(@ztotalcoin),free(@zprestige),
      free(@zcardwhite),free(@zcardblue),free(@zcardgreen),free(@zcardred),free(@zcardblack),
      free(@zcoinwhite),free(@zcoinblue),free(@zcoingreen),free(@zcoinred),free(@zcoinblack),free(@zcoingold),
      send(@main, display, new(@zprestige,text(ZPrestige,center,large)), point(572, 456)),
      send(@main, display, new(@ztotalcoin,text(ZTotalCoin,center,large)), point(563, 489)),
      send(@main, display, new(@zcoingold,text(ZCoinGold,center,large)), point(591, 514)),
      send(@main, display, new(@zcardwhite,text(ZCardWhite,center,large)), point(608, 489)),
      send(@main, display, new(@zcoinwhite,text(ZCoinWhite,center,large)), point(628, 489)),
      send(@main, display, new(@zcardgreen,text(ZCardBlue,center,large)), point(650, 489)),
      send(@main, display, new(@zcoinblue,text(ZCoinBlue,center,large)), point(672, 489)),
      send(@main, display, new(@zcardblue,text(ZCardGreen,center,large)), point(695, 489)),
      send(@main, display, new(@zcoingreen,text(ZCoinGreen,center,large)), point(716, 489)),
      send(@main, display, new(@zcardred,text(ZCardRed,center,large)), point(738, 489)),
      send(@main, display, new(@zcoinred,text(ZCoinRed,center,large)), point(758, 489)),
      send(@main, display, new(@zcardblack,text(ZCardBlack,center,large)), point(780, 489)),
      send(@main, display, new(@zcoinblack,text(ZCoinBlack,center,large)), point(803, 489))
    );
    (
      PlayerCount == 4,
      playerNo(1,X),
      playerNo(2,Y),
      playerNo(3,Z),
      playerNo(4,T),

      cardPower(X,XCardWhite,XCardBlue,XCardGreen,XCardRed,XCardBlack),
      coinPower(X,XCoinWhite,XCoinBlue,XCoinGreen,XCoinRed,XCoinBlack,XCoinGold),
      prestigePower(X,XPrestige),
      XTotalCoin is XCoinWhite+XCoinBlue+XCoinGreen+XCoinRed+XCoinBlack+XCoinGold,
      free(@xtotalcoin),free(@xprestige),
      free(@xcardwhite),free(@xcardblue),free(@xcardgreen),free(@xcardred),free(@xcardblack),
      free(@xcoinwhite),free(@xcoinblue),free(@xcoingreen),free(@xcoinred),free(@xcoinblack),free(@xcoingold),
      send(@main, display, new(@xprestige,text(XPrestige,center,large)), point(44, 456)),
      send(@main, display, new(@xtotalcoin,text(XTotalCoin,center,large)), point(35, 489)),
      send(@main, display, new(@xcoingold,text(XCoinGold,center,large)), point(62, 514)),
      send(@main, display, new(@xcardwhite,text(XCardWhite,center,large)), point(80, 489)),
      send(@main, display, new(@xcoinwhite,text(XCoinWhite,center,large)), point(100, 489)),
      send(@main, display, new(@xcardgreen,text(XCardBlue,center,large)), point(122, 489)),
      send(@main, display, new(@xcoinblue,text(XCoinBlue,center,large)), point(144, 489)),
      send(@main, display, new(@xcardblue,text(XCardGreen,center,large)), point(167, 489)),
      send(@main, display, new(@xcoingreen,text(XCoinGreen,center,large)), point(188, 489)),
      send(@main, display, new(@xcardred,text(XCardRed,center,large)), point(210, 489)),
      send(@main, display, new(@xcoinred,text(XCoinRed,center,large)), point(230, 489)),
      send(@main, display, new(@xcardblack,text(XCardBlack,center,large)), point(252, 489)),
      send(@main, display, new(@xcoinblack,text(XCoinBlack,center,large)), point(274, 489)),

      cardPower(Y,YCardWhite,YCardBlue,YCardGreen,YCardRed,YCardBlack),
      coinPower(Y,YCoinWhite,YCoinBlue,YCoinGreen,YCoinRed,YCoinBlack,YCoinGold),
      prestigePower(Y,YPrestige),
      YTotalCoin is YCoinWhite+YCoinBlue+YCoinGreen+YCoinRed+YCoinBlack+YCoinGold,
      free(@ytotalcoin),free(@yprestige),
      free(@ycardwhite),free(@ycardblue),free(@ycardgreen),free(@ycardred),free(@ycardblack),
      free(@ycoinwhite),free(@ycoinblue),free(@ycoingreen),free(@ycoinred),free(@ycoinblack),free(@ycoingold),
      send(@main, display, new(@yprestige,text(YPrestige,center,large)), point(307, 456)),
      send(@main, display, new(@ytotalcoin,text(YTotalCoin,center,large)), point(298, 489)),
      send(@main, display, new(@ycoingold,text(YCoinGold,center,large)), point(326, 514)),
      send(@main, display, new(@ycardwhite,text(YCardWhite,center,large)), point(343, 489)),
      send(@main, display, new(@ycoinwhite,text(YCoinWhite,center,large)), point(363, 489)),
      send(@main, display, new(@ycardgreen,text(YCardBlue,center,large)), point(385, 489)),
      send(@main, display, new(@ycoinblue,text(YCoinBlue,center,large)), point(407, 489)),
      send(@main, display, new(@ycardblue,text(YCardGreen,center,large)), point(430, 489)),
      send(@main, display, new(@ycoingreen,text(YCoinGreen,center,large)), point(451, 489)),
      send(@main, display, new(@ycardred,text(YCardRed,center,large)), point(473, 489)),
      send(@main, display, new(@ycoinred,text(YCoinRed,center,large)), point(493, 489)),
      send(@main, display, new(@ycardblack,text(YCardBlack,center,large)), point(515, 489)),
      send(@main, display, new(@ycoinblack,text(YCoinBlack,center,large)), point(538, 489)),

      cardPower(Z,ZCardWhite,ZCardBlue,ZCardGreen,ZCardRed,ZCardBlack),
      coinPower(Z,ZCoinWhite,ZCoinBlue,ZCoinGreen,ZCoinRed,ZCoinBlack,ZCoinGold),
      prestigePower(Z,ZPrestige),
      ZTotalCoin is ZCoinWhite+ZCoinBlue+ZCoinGreen+ZCoinRed+ZCoinBlack+ZCoinGold,
      free(@ztotalcoin),free(@zprestige),
      free(@zcardwhite),free(@zcardblue),free(@zcardgreen),free(@zcardred),free(@zcardblack),
      free(@zcoinwhite),free(@zcoinblue),free(@zcoingreen),free(@zcoinred),free(@zcoinblack),free(@zcoingold),
      send(@main, display, new(@zprestige,text(ZPrestige,center,large)), point(572, 456)),
      send(@main, display, new(@ztotalcoin,text(ZTotalCoin,center,large)), point(563, 489)),
      send(@main, display, new(@zcoingold,text(ZCoinGold,center,large)), point(591, 514)),
      send(@main, display, new(@zcardwhite,text(ZCardWhite,center,large)), point(608, 489)),
      send(@main, display, new(@zcoinwhite,text(ZCoinWhite,center,large)), point(628, 489)),
      send(@main, display, new(@zcardgreen,text(ZCardBlue,center,large)), point(650, 489)),
      send(@main, display, new(@zcoinblue,text(ZCoinBlue,center,large)), point(672, 489)),
      send(@main, display, new(@zcardblue,text(ZCardGreen,center,large)), point(695, 489)),
      send(@main, display, new(@zcoingreen,text(ZCoinGreen,center,large)), point(716, 489)),
      send(@main, display, new(@zcardred,text(ZCardRed,center,large)), point(738, 489)),
      send(@main, display, new(@zcoinred,text(ZCoinRed,center,large)), point(758, 489)),
      send(@main, display, new(@zcardblack,text(ZCardBlack,center,large)), point(780, 489)),
      send(@main, display, new(@zcoinblack,text(ZCoinBlack,center,large)), point(803, 489)),

      cardPower(T,TCardWhite,TCardBlue,TCardGreen,TCardRed,TCardBlack),
      coinPower(T,TCoinWhite,TCoinBlue,TCoinGreen,TCoinRed,TCoinBlack,TCoinGold),
      prestigePower(T,TPrestige),
      TTotalCoin is TCoinWhite+TCoinBlue+TCoinGreen+TCoinRed+TCoinBlack+TCoinGold,
      free(@ttotalcoin),free(@tprestige),
      free(@tcardwhite),free(@tcardblue),free(@tcardgreen),free(@tcardred),free(@tcardblack),
      free(@tcoinwhite),free(@tcoinblue),free(@tcoingreen),free(@tcoinred),free(@tcoinblack),free(@tcoingold),
      send(@main, display, new(@tprestige,text(TPrestige,center,large)), point(839, 456)),
      send(@main, display, new(@ttotalcoin,text(TTotalCoin,center,large)), point(831, 489)),
      send(@main, display, new(@tcoingold,text(TCoinGold,center,large)), point(861, 514)),
      send(@main, display, new(@tcardwhite,text(TCardWhite,center,large)), point(876, 489)),
      send(@main, display, new(@tcoinwhite,text(TCoinWhite,center,large)), point(896, 489)),
      send(@main, display, new(@tcardgreen,text(TCardBlue,center,large)), point(919, 489)),
      send(@main, display, new(@tcoinblue,text(TCoinBlue,center,large)), point(940, 489)),
      send(@main, display, new(@tcardblue,text(TCardGreen,center,large)), point(963, 489)),
      send(@main, display, new(@tcoingreen,text(TCoinGreen,center,large)), point(984, 489)),
      send(@main, display, new(@tcardred,text(TCardRed,center,large)), point(1005, 489)),
      send(@main, display, new(@tcoinred,text(TCoinRed,center,large)), point(1025, 489)),
      send(@main, display, new(@tcardblack,text(TCardBlack,center,large)), point(1047, 489)),
      send(@main, display, new(@tcoinblack,text(TCoinBlack,center,large)), point(1070, 489))
    )
  ).

